In [237]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import permutation_test_score
from sklearn.model_selection import KFold
from __future__ import division 

In [270]:
#six way classification 
#final version
gb='bad'
layer_list=['conv1','conv2','conv3','conv4','conv5','fc6','fc7',"fc8"]
clf = svm.SVC(kernel='linear', C=2.03)   
#cv = ShuffleSplit(n_splits=10, test_size=0.1, random_state=0)
class_good=[27,31,39,46,25,42] #total number of image for each class 
class_bad=[34,39,32,31,42,32]
y_good=[1]*27+[2]*31+[3]*39+[4]*46+[5]*25+[6]*42 
#y-true
y_good=np.asarray(y_good)
y_bad=[1]*34+[2]*39+[3]*32+[4]*31+[5]*42+[6]*32
#y-true
y_bad=np.asarray(y_bad)
if gb=='good':
    score_dict_g={}
    y=y_good
    for layer in layer_list:
        print layer
        list0= open("/Users/manoj/good_bad_placecnn/features/good/good_"+layer+".txt", "r") 
        X_good=[]
        for line in list0:
            X_good.append(line.split())
        X_good=[[float(j) for j in i] for i in X_good]
        X_good=np.asarray(X_good)
        X=X_good
        ss=ShuffleSplit(n_splits=10,random_state=0,test_size=0.1)
        sum1 = np.matrix([[0 for i in range(6)] for j in range(6)])
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]      
            y_pred = clf.fit(X_train, y_train).predict(X_test)         
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=sum1+cm
        print sum1
        cmm=[]
        for k in range(0,6):
            row=[]
            for p in range(0,6):    
                row.extend([float(format(sum1.item((k,p))/class_good[k],'.3f'))])
            cmm.append(row)
        confusion_mtx=np.matrix(np.array(cmm))
        print confusion_mtx

else: 
    score_dict_b={}
    y=y_bad
    for layer in layer_list:
        print layer
        list0= open("/Users/manoj/good_bad_placecnn/features/good/good_"+layer+".txt", "r")
        X_bad=[]
        for line in list0:
            X_bad.append(line.split())
        X_bad=[[float(j) for j in i] for i in X_bad]
        X_bad=np.asarray(X_bad)
        X=X_bad
        ss=ShuffleSplit(n_splits=10,random_state=0,test_size=0.1)
        sum1 = np.matrix([[0 for i in range(6)] for j in range(6)])
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            y_pred = clf.fit(X_train, y_train).predict(X_test)
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=sum1+cm
        print sum1
        cmm=[]
        for k in range(0,6):
            row=[]
            for p in range(0,6):    
                row.extend([float(format(sum1.item((k,p))/class_bad[k],'.3f'))])
            cmm.append(row)
        confusion_mtx=np.matrix(np.array(cmm))
        print confusion_mtx
            
   

conv1
[[21  0  4  2  4  0]
 [ 6 23  8  0  0  2]
 [ 1  4 14  1  1  0]
 [ 6  3  2  7  3  2]
 [ 2  9  8 11 35 15]
 [ 0  1  0  1  4 10]]
[[ 0.618  0.     0.118  0.059  0.118  0.   ]
 [ 0.154  0.59   0.205  0.     0.     0.051]
 [ 0.031  0.125  0.438  0.031  0.031  0.   ]
 [ 0.194  0.097  0.065  0.226  0.097  0.065]
 [ 0.048  0.214  0.19   0.262  0.833  0.357]
 [ 0.     0.031  0.     0.031  0.125  0.312]]
conv2
[[24  3  0  0  0  0]
 [ 7 26  8  0  1  0]
 [ 0  6 18  1  0  0]
 [ 3  3  2 17  6  0]
 [ 2  2  8  4 32  5]
 [ 0  0  0  0  8 24]]
[[ 0.706  0.088  0.     0.     0.     0.   ]
 [ 0.179  0.667  0.205  0.     0.026  0.   ]
 [ 0.     0.188  0.562  0.031  0.     0.   ]
 [ 0.097  0.097  0.065  0.548  0.194  0.   ]
 [ 0.048  0.048  0.19   0.095  0.762  0.119]
 [ 0.     0.     0.     0.     0.25   0.75 ]]
conv3
[[27  3  1  0  0  0]
 [ 7 28  7  1  1  0]
 [ 0  5 19  1  0  0]
 [ 0  3  5 14  5  0]
 [ 2  1  4  6 30  3]
 [ 0  0  0  0 11 26]]
[[ 0.794  0.088  0.029  0.     0.     0.   ]
 [ 0.179  0.71