In [116]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
#from sklearn.decomposition import PCA
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import permutation_test_score
from sklearn.model_selection import KFold


In [94]:
#six way classification 
#original one 
gb='good'
#layer_list=['conv1','conv2','conv3']
layer_list=['conv1','conv2','conv3','conv4','conv5','fc6','fc7','fc8']
#layer_list=['conv1','conv2','conv3','conv4','conv5','fc6','fc7']
clf = svm.SVC(kernel='linear', C=2.03)   
#cv = ShuffleSplit(n_splits=10, test_size=0.1, random_state=0)
y_good=[1]*27+[2]*31+[3]*39+[4]*46+[5]*25+[6]*42 
#y-true
y_good=np.asarray(y_good)
y_bad=[1]*34+[2]*39+[3]*32+[4]*31+[5]*42+[6]*32
#y-true
y_bad=np.asarray(y_bad)
if gb=='good':
    score_dict_g={}
    y=y_good
    for layer in layer_list:
        #print(layer)
        list0= open("/Users/manoj/good_bad_placecnn/features/good/good_"+layer+".txt", "r") 
        X_good=[]
        for line in list0:
            X_good.append(line.split())
        X_good=[[float(j) for j in i] for i in X_good]
        X_good=np.asarray(X_good)
        X=X_good
        #kf = KFold(n_splits=10)
        ss=ShuffleSplit(n_splits=10,random_state=0)
        accuracy=[]
        avg_score_list=[]
        #kf = KFold(len(y), n_splits=10)
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            #model.fit(X_train, y_train)
            y_pred = clf.fit(X_train, y_train).predict(X_test)
            #print y_test
            #print y_pred
            #print(len(y_test))
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=np.sum(np.diagonal(cm))
            accuracy.extend([sum1])
            avg_score=np.mean(accuracy)
            avg_score_list.extend([avg_score])
            #print cm 
        print avg_score_list
#         print(len(X_train))
#         print(X_test)
#         print(y_train)
        #print(len(y_test))
      
        #score_good=cross_val_score(clf, X, y, cv=cv)
        #X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.1, random_state=0 )
        #svm = SVC(kernel='linear')
        #y_pred = clf.fit(X_train, y_train).predict(X_test)
        #print(confusion_matrix(y_test, y_pred))
    

# Run classifier, using a model that is too regularized (C too low) to see
# the impact on the results

else: 
    score_dict_b={}
    y=y_bad
    for layer in layer_list:
        print(layer)
        list0= open('/Users/sczha/Documents/RESEARCH/features/'+gb+"/"+gb+"_"+layer+".txt", "r")
        X_bad=[]
        for line in list0:
            X_bad.append(line.split())
        X_bad=[[float(j) for j in i] for i in X_bad]
        X_bad=np.asarray(X_bad)
        X=X_bad
        ss=ShuffleSplit(n_splits=10,random_state=0)
        accuracy=[]
        #kf = KFold(len(y), n_splits=10)
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            #model.fit(X_train, y_train)
            y_pred = clf.fit(X_train, y_train).predict(X_test)
            #print y_test
            #print y_pred
            #print(len(y_test))
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=np.sum(np.diagonal(cm))
            accuracy.extend([sum1])
            avg_score=np.mean(accuracy)
            #print cm 
        print avg_score
        #X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.1, random_state=0)
        
        y_pred = clf.fit(X_train, y_train).predict(X_test)
        cm=confusion_matrix(y_pred, y_test)
        print cm.mean()
        #score_bad=cross_val_score(clf, X, y, cv=cv)
        #svm = SVC(kernel='linear')


[13.0, 14.0, 13.666666666666666, 13.75, 13.4, 13.833333333333334, 13.714285714285714, 13.75, 14.0, 13.9]
[18.0, 17.5, 18.333333333333332, 18.0, 18.399999999999999, 18.166666666666668, 18.428571428571427, 18.5, 18.555555555555557, 18.699999999999999]
[19.0, 19.0, 19.0, 19.25, 19.399999999999999, 19.166666666666668, 19.428571428571427, 19.5, 19.555555555555557, 19.600000000000001]
[20.0, 19.5, 19.0, 19.25, 19.399999999999999, 19.166666666666668, 19.428571428571427, 19.5, 19.444444444444443, 19.5]
[20.0, 20.0, 20.333333333333332, 20.25, 20.0, 19.833333333333332, 20.0, 20.125, 20.222222222222221, 20.199999999999999]
[21.0, 20.5, 20.666666666666668, 20.75, 20.800000000000001, 20.666666666666668, 20.714285714285715, 20.75, 20.777777777777779, 20.800000000000001]
[20.0, 20.5, 20.666666666666668, 20.75, 20.800000000000001, 20.333333333333332, 20.428571428571427, 20.5, 20.555555555555557, 20.600000000000001]
[21.0, 21.0, 21.0, 21.0, 20.800000000000001, 20.333333333333332, 20.285714285714285, 20

In [97]:
print avg_score

20.4


In [98]:
print cm.mean()

0.583333333333


In [99]:
print cm 

[[3 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 3 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [125]:
#six way classification 
#original one 
gb='good'
#layer_list=['conv1','conv2','conv3']
layer_list=['fc6']
#layer_list=['conv1','conv2','conv3','conv4','conv5','fc6','fc7']
clf = svm.SVC(kernel='linear', C=2.03)   
#cv = ShuffleSplit(n_splits=10, test_size=0.1, random_state=0)
y_good=[1]*27+[2]*31+[3]*39+[4]*46+[5]*25+[6]*42 
#y-true
y_good=np.asarray(y_good)
y_bad=[1]*34+[2]*39+[3]*32+[4]*31+[5]*42+[6]*32
#y-true
y_bad=np.asarray(y_bad)
if gb=='good':
    score_dict_g={}
    y=y_good
    for layer in layer_list:
        #print(layer)
        list0= open("/Users/manoj/good_bad_placecnn/features/good/good_"+layer+".txt", "r") 
        X_good=[]
        for line in list0:
            X_good.append(line.split())
        X_good=[[float(j) for j in i] for i in X_good]
        X_good=np.asarray(X_good)
        X=X_good
        #kf = KFold(n_splits=10)
        ss=ShuffleSplit(n_splits=4,random_state=0)
        accuracy=[]
        avg_score_list=[]
        cm_mean_list=[]
        #kf = KFold(len(y), n_splits=10)
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            #model.fit(X_train, y_train)
            y_pred = clf.fit(X_train, y_train).predict(X_test)
            #print y_test
            #print y_pred
            #print(len(y_test))
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            cm_mean=cm.mean()
            cm_mean_list.extend([cm_mean])
            sum1=np.sum(np.diagonal(cm))
            accuracy.extend([sum1])
            avg_score=np.mean(accuracy)
            avg_score_list.extend([avg_score])
            print cm 
        print avg_score_list
        print cm_mean_list
        print accuracy
#         print(len(X_train))
#         print(X_test)
#         print(y_train)
        #print(len(y_test))
      
        #score_good=cross_val_score(clf, X, y, cv=cv)
        #X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.1, random_state=0 )
        #svm = SVC(kernel='linear')
        #y_pred = clf.fit(X_train, y_train).predict(X_test)
        #print(confusion_matrix(y_test, y_pred))
    

# Run classifier, using a model that is too regularized (C too low) to see
# the impact on the results

else: 
    score_dict_b={}
    y=y_bad
    for layer in layer_list:
        print(layer)
        list0= open('/Users/sczha/Documents/RESEARCH/features/'+gb+"/"+gb+"_"+layer+".txt", "r")
        X_bad=[]
        for line in list0:
            X_bad.append(line.split())
        X_bad=[[float(j) for j in i] for i in X_bad]
        X_bad=np.asarray(X_bad)
        X=X_bad
        ss=ShuffleSplit(n_splits=4,random_state=0)
        accuracy=[]
        #kf = KFold(len(y), n_splits=10)
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            #model.fit(X_train, y_train)
            y_pred = clf.fit(X_train, y_train).predict(X_test)
            #print y_test
            #print y_pred
            #print(len(y_test))
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=np.sum(np.diagonal(cm))
            accuracy.extend([sum1])
            avg_score=np.mean(accuracy)
            print cm 
        #print avg_score
        #X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.1, random_state=0)
        
#         y_pred = clf.fit(X_train, y_train).predict(X_test)
#         cm=confusion_matrix(y_pred, y_test)
#         print cm.mean()

[[3 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 4]]
[[1 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 5 0 0 0]
 [0 1 0 6 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 3]]
[[4 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
[[2 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 6 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 3]]
[21.0, 20.5, 20.666666666666668, 20.75]
[0.58333333333333337, 0.58333333333333337, 0.58333333333333337, 0.58333333333333337]
[21, 20, 21, 21]


In [ ]:
[21, 20, 21

In [107]:
print cm

[[3 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 3 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [105]:
print cm.mean()

0.583333333333
