In [4]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import permutation_test_score
from sklearn.model_selection import KFold
from __future__ import division 

In [5]:
#six way classification 
#final version
gb='good'
layer_list=['conv1','conv2','conv3','conv4','conv5','fc6','fc7',"fc8"]
clf = svm.SVC(kernel='linear', C=2.03)   
#cv = ShuffleSplit(n_splits=10, test_size=0.1, random_state=0)
class_good=[27,31,39,46,25,42] #total number of image for each class 
class_bad=[34,39,32,31,42,32]
#y_good=[1]*27+[2]*31+[3]*39+[4]*46+[5]*25+[6]*42 
y_good=[1]*60+[2]*60+[3]*60+[4]*60+[5]*60+[6]*60
y_good=np.asarray(y_good)
#y_bad=[1]*34+[2]*39+[3]*32+[4]*31+[5]*42+[6]*32
y_bad=[1]*60+[2]*60+[3]*60+[4]*60+[5]*60+[6]*60
y_bad=np.asarray(y_bad)
if gb=='good':
    score_dict_g={}
    y=y_good
    for layer in layer_list:
        print layer
        list0= open('/Users/manoj/good_bad_placecnn/features/'+gb+"360/"+gb+"_"+layer+"_360.txt", "r") 
        X_good=[]
        for line in list0:
            X_good.append(line.split())
        X_good=[[float(j) for j in i] for i in X_good]
        X_good=np.asarray(X_good)
        X=X_good
        ss=ShuffleSplit(n_splits=4,random_state=0,test_size=0.25)
        sum1 = np.matrix([[0 for i in range(6)] for j in range(6)])
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]      
            y_pred = clf.fit(X_train, y_train).predict(X_test)         
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=sum1+cm
        print sum1
        cmm=[]
        for k in range(0,6):
            row=[]
            s=0
            for q in range(0,6):
                s=s+sum1.item((k,q))
            for p in range(0,6):    
                row.extend([float(format(sum1.item((k,p))/s,'.3f'))])
            cmm.append(row)
        confusion_mtx=np.matrix(np.array(cmm))
        print confusion_mtx

else: 
    score_dict_b={}
    y=y_bad
    for layer in layer_list:
        print layer
        list0= open('/Users/manoj/good_bad_placecnn/features/'+gb+"360/"+gb+"_"+layer+"_360.txt", "r")
        X_bad=[]
        for line in list0:
            X_bad.append(line.split())
        X_bad=[[float(j) for j in i] for i in X_bad]
        X_bad=np.asarray(X_bad)
        X=X_bad
        ss=ShuffleSplit(n_splits=4,random_state=0,test_size=0.25)
        sum1 = np.matrix([[0 for i in range(6)] for j in range(6)])
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            y_pred = clf.fit(X_train, y_train).predict(X_test)
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=sum1+cm
        print sum1
        cmm=[]
        for k in range(0,6):
            row=[]
            s=0
            for p in range (0,6):
                s=s+sum1.item((k,p))
            for q in range(0,6):
                row.extend([float(format(sum1.item((k,q))/s,'.3f'))])
            cmm.append(row)
        confusion_mtx=np.matrix(np.array(cmm))
        print confusion_mtx
            
   

conv1
[[52  0  0  2  2  0]
 [ 0 39  7  4  0  5]
 [ 0  4 50  1  0  0]
 [13  0  0 40  2  8]
 [ 5  3  0 17 50  5]
 [ 0  8  1  3  4 35]]
[[ 0.929  0.     0.     0.036  0.036  0.   ]
 [ 0.     0.709  0.127  0.073  0.     0.091]
 [ 0.     0.073  0.909  0.018  0.     0.   ]
 [ 0.206  0.     0.     0.635  0.032  0.127]
 [ 0.062  0.037  0.     0.212  0.625  0.062]
 [ 0.     0.157  0.02   0.059  0.078  0.686]]
conv2
[[61  0  0  1  0  0]
 [ 0 51  0  4  0  3]
 [ 0  0 58  2  0  0]
 [ 5  0  0 57  1  0]
 [ 4  0  0  2 57  0]
 [ 0  3  0  1  0 50]]
[[ 0.984  0.     0.     0.016  0.     0.   ]
 [ 0.     0.879  0.     0.069  0.     0.052]
 [ 0.     0.     0.967  0.033  0.     0.   ]
 [ 0.079  0.     0.     0.905  0.016  0.   ]
 [ 0.063  0.     0.     0.032  0.905  0.   ]
 [ 0.     0.056  0.     0.019  0.     0.926]]
conv3
[[68  0  0  1  0  0]
 [ 0 51  0  2  0  2]
 [ 0  0 58  1  0  0]
 [ 0  0  0 62  0  0]
 [ 2  0  0  1 58  0]
 [ 0  3  0  0  0 51]]
[[ 0.986  0.     0.     0.014  0.     0.   ]
 [ 0.     0.92

In [6]:
#six way classification 
#final version
gb='bad'
layer_list=['conv1','conv2','conv3','conv4','conv5','fc6','fc7',"fc8"]
clf = svm.SVC(kernel='linear', C=2.03)   
#cv = ShuffleSplit(n_splits=10, test_size=0.1, random_state=0)
class_good=[27,31,39,46,25,42] #total number of image for each class 
class_bad=[34,39,32,31,42,32]
#y_good=[1]*27+[2]*31+[3]*39+[4]*46+[5]*25+[6]*42 
y_good=[1]*60+[2]*60+[3]*60+[4]*60+[5]*60+[6]*60
y_good=np.asarray(y_good)
#y_bad=[1]*34+[2]*39+[3]*32+[4]*31+[5]*42+[6]*32
y_bad=[1]*60+[2]*60+[3]*60+[4]*60+[5]*60+[6]*60
y_bad=np.asarray(y_bad)
if gb=='good':
    score_dict_g={}
    y=y_good
    for layer in layer_list:
        print layer
        list0= open('/Users/manoj/good_bad_placecnn/features/'+gb+"360/"+gb+"_"+layer+"_360.txt", "r") 
        X_good=[]
        for line in list0:
            X_good.append(line.split())
        X_good=[[float(j) for j in i] for i in X_good]
        X_good=np.asarray(X_good)
        X=X_good
        ss=ShuffleSplit(n_splits=4,random_state=0,test_size=0.25)
        sum1 = np.matrix([[0 for i in range(6)] for j in range(6)])
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]      
            y_pred = clf.fit(X_train, y_train).predict(X_test)         
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=sum1+cm
        print sum1
        cmm=[]
        for k in range(0,6):
            row=[]
            s=0
            for q in range(0,6):
                s=s+sum1.item((k,q))
            for p in range(0,6):    
                row.extend([float(format(sum1.item((k,p))/s,'.3f'))])
            cmm.append(row)
        confusion_mtx=np.matrix(np.array(cmm))
        print confusion_mtx

else: 
    score_dict_b={}
    y=y_bad
    for layer in layer_list:
        print layer
        list0= open('/Users/manoj/good_bad_placecnn/features/'+gb+"360/"+gb+"_"+layer+"_360.txt", "r")
        X_bad=[]
        for line in list0:
            X_bad.append(line.split())
        X_bad=[[float(j) for j in i] for i in X_bad]
        X_bad=np.asarray(X_bad)
        X=X_bad
        ss=ShuffleSplit(n_splits=4,random_state=0,test_size=0.25)
        sum1 = np.matrix([[0 for i in range(6)] for j in range(6)])
        for train_index, test_index in ss.split(X):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            y_pred = clf.fit(X_train, y_train).predict(X_test)
            cm=confusion_matrix(y_pred, y_test,labels=range(1,7))
            sum1=sum1+cm
        print sum1
        cmm=[]
        for k in range(0,6):
            row=[]
            s=0
            for p in range (0,6):
                s=s+sum1.item((k,p))
            for q in range(0,6):
                row.extend([float(format(sum1.item((k,q))/s,'.3f'))])
            cmm.append(row)
        confusion_mtx=np.matrix(np.array(cmm))
        print confusion_mtx
            
   

conv1
[[15  2 10 18 16  3]
 [ 5  8  5 11  2  9]
 [13 12 27  5  4  3]
 [18  7  8 18 14 13]
 [16 18  6  9 22  1]
 [ 3  7  2  6  0 24]]
[[ 0.234  0.031  0.156  0.281  0.25   0.047]
 [ 0.125  0.2    0.125  0.275  0.05   0.225]
 [ 0.203  0.188  0.422  0.078  0.062  0.047]
 [ 0.231  0.09   0.103  0.231  0.179  0.167]
 [ 0.222  0.25   0.083  0.125  0.306  0.014]
 [ 0.071  0.167  0.048  0.143  0.     0.571]]
conv2
[[29  1  8  5 15  0]
 [ 6 31  3 15  1  6]
 [ 8  8 41  2  2  0]
 [ 9  6  1 30  3  9]
 [18  4  5  8 37  1]
 [ 0  4  0  7  0 37]]
[[ 0.5    0.017  0.138  0.086  0.259  0.   ]
 [ 0.097  0.5    0.048  0.242  0.016  0.097]
 [ 0.131  0.131  0.672  0.033  0.033  0.   ]
 [ 0.155  0.103  0.017  0.517  0.052  0.155]
 [ 0.247  0.055  0.068  0.11   0.507  0.014]
 [ 0.     0.083  0.     0.146  0.     0.771]]
conv3
[[30  1  4  6 17  0]
 [ 8 30  2 15  0  5]
 [ 9  9 42  1  2  0]
 [ 9  6  3 31  2  1]
 [14  5  7  9 37  0]
 [ 0  3  0  5  0 47]]
[[ 0.517  0.017  0.069  0.103  0.293  0.   ]
 [ 0.133  0.5 